import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useAuth } from '../context/AuthContext';
import { User, Settings, Info, Briefcase, MapPin, Phone, Mail, LogOut } from 'lucide-react';
import { ProfileHeader } from '../components/organisms/Profile/ProfileHeader';
import { ProfileMenuItem } from '../components/molecules/ProfileMenuItem';
export const Profile = () => {
    const { profile } = useAuth();
    return (_jsxs("div", { className: "flex-1 flex flex-col bg-white h-full pb-32 overflow-y-auto custom-scrollbar w-full max-w-md mx-auto", children: [_jsx(ProfileHeader, { profile: profile }), _jsx("div", { className: "h-2 w-full bg-gray-50" }), _jsxs("div", { className: "flex flex-col px-5 py-2", children: [_jsx(ProfileMenuItem, { icon: User, title: "Personal Details", subtitle: "Manage your identity information" }), _jsx(ProfileMenuItem, { icon: Settings, title: "Settings" }), _jsx(ProfileMenuItem, { icon: MapPin, title: "Addresses", subtitle: "Manage your residential details", isNew: true }), _jsx(ProfileMenuItem, { icon: Phone, title: "Emergency Contacts", subtitle: "Manage who we alert" }), _jsx(ProfileMenuItem, { icon: Briefcase, title: "Business Profile", subtitle: "Automate work security expenses" })] }), _jsx("div", { className: "h-2 w-full bg-gray-50 my-2" }), _jsxs("div", { className: "flex flex-col px-5 py-2", children: [_jsx(ProfileMenuItem, { icon: Mail, title: "Support & Feedback" }), _jsx(ProfileMenuItem, { icon: Info, title: "About e-SAPS" }), _jsx("div", { className: "mt-4 pb-4", children: _jsxs("button", { className: "w-full flex items-center py-4 text-red-600 hover:bg-red-50 transition-colors rounded-xl px-4 -ml-4", children: [_jsx(LogOut, { className: "w-[22px] h-[22px] mr-4", strokeWidth: 1.5 }), _jsx("span", { className: "text-[16px] font-medium", children: "Sign Out" })] }) })] })] }));
};
